
Resources:
  MetricsStack:
    Condition: CreateMetricsStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/buildkite-cloudwatch-metrics-publisher/master/cloudwatch-metrics-publisher.json
      Parameters:
        BuildkiteApiAccessToken: $(BuildkiteApiAccessToken)
        BuildkiteOrgSlug: $(BuildkiteOrgSlug)
        KeyName: $(KeyName)
        QueueName: $(BuildkiteQueue)
        PollInterval: 15s
        VpcId: !If [
          "CreateVpcResources",
          $(Vpc),
          $(VpcId)
        ]
        Subnets: !If [
          "CreateVpcResources",
          "$(Subnet0),$(Subnet1),$(Subnet2)",
          !Join [ ",", $(Subnets) ]
        ]
      Tags:
        - Key: Role
          Value: buildkite-metrics
        - Key: Name
          Value: buildkite-metrics
