
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Scheduled Action for Auto-scaling Group
        Parameters:
        - ScheduledUpRecurrence
        - ScheduledUpDesiredSize
        - ScheduledUpMinSize
        - ScheduledDownRecurrence
        - ScheduledDownDesiredSize
        - ScheduledDownMinSize

Parameters:
  ScheduledUpRecurrence:
    Description: The Unix cron expression for bring up more agents, e.g. bring up agents at 8 AM everyday
    Type: String
    Default: 0 21 * * *

  ScheduledUpDesiredSize:
    Description: The desired size for bring up more agents
    Type: Number
    Default: 1

  ScheduledUpMinSize:
    Description: The min size for bring up more agents
    Type: Number
    Default: 1

  ScheduledDownRecurrence:
    Description: The Unix cron expression for non-busy time, e.g. shut down agents at 8 PM everyday
    Type: String
    Default: 0 9 * * *

  ScheduledDownDesiredSize:
    Description: The desired size of agents for non-busy time
    Type: Number
    Default: 0

  ScheduledDownMinSize:
    Description: The min size of agents for non-busy time
    Type: Number
    Default: 0

Resources:
  AgentLaunchConfiguration:
    Metadata:
      # see http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-init.html
      AWS::CloudFormation::Init:
        config:
          commands:
            04-fetch-authorized-users-s3:
              test: test -n "$(AuthorizedUsersUrl)"
              command: |
                #!/bin/bash -eu

                cat << EOF > /etc/cron.hourly/authorized_keys
                case "$(AuthorizedUsersUrl)" in
                    s3://*)
                      aws s3 cp "$(AuthorizedUsersUrl)" /tmp/authorized_keys;;
                    *)
                      curl --silent -f "$(AuthorizedUsersUrl)" > /tmp/authorized_keys;;
                esac

                if [ ! -f /home/ec2-user/.ssh/original_authorized_keys ]; then
                   cp /home/ec2-user/.ssh/authorized_keys /home/ec2-user/.ssh/original_authorized_keys
                fi

                (cat /tmp/authorized_keys; echo; cat /home/ec2-user/.ssh/original_authorized_keys; echo) | sort | uniq > /home/ec2-user/.ssh/authorized_keys

                chmod 600 /home/ec2-user/.ssh/authorized_keys
                chown ec2-user: /home/ec2-user/.ssh/authorized_keys
                EOF

                chmod +x /etc/cron.hourly/authorized_keys

                /etc/cron.hourly/authorized_keys

  ScheduledActionAgentUp:
    Type: AWS::AutoScaling::ScheduledAction
    Properties:
      AutoScalingGroupName: $(AgentAutoScaleGroup)
      MaxSize: $(MaxSize)
      MinSize: $(ScheduledUpMinSize)
      DesiredCapacity: $(ScheduledUpDesiredSize)
      Recurrence: $(ScheduledUpRecurrence)

  ScheduledActionAgentDown:
    Type: AWS::AutoScaling::ScheduledAction
    Properties:
      AutoScalingGroupName: $(AgentAutoScaleGroup)
      MaxSize: $(MaxSize)
      MinSize: $(ScheduledDownMinSize)
      DesiredCapacity: $(ScheduledDownDesiredSize)
      Recurrence: $(ScheduledDownRecurrence)
